name: i2pbrowser
version: '0.04a'
summary: I2P Browser Launcher
base: core18
description: |
  This snap contains a script which automatically configures and launches a
  Firefox browser configured for i2p.

apps:
  i2pbrowser:
    command: I2PBrowser.sh
    desktop: i2pbrowser-firefox.desktop
  #i2pbrowser-private:
    #command: I2PBrowser-Private.sh
    #desktop: i2pbrowser-firefox-private.desktop

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  i2pbrowser:
    source: https://github.com/eyedeekay/firefox.profile.i2p.git
    source-subdir: "."
    plugin: make
    stage:
      - /usr/share/applications/i2pbrowser-firefox.desktop
      #- firefox.launchers/snap/gnulinux/i2pbrowser-firefox-private.desktop
    prime:
      - /usr/share/applications/i2pbrowser-firefox.desktop
      #- firefox.launchers/snap/gnulinux/i2pbrowser-firefox-private.desktop
    stage-packages: [ firefox ]
