name: i2pbrowser
version: '0.04a'
summary: I2P Browser Launcher
base: core18
description: |
  This snap contains a script which automatically configures and launches a
  Firefox browser configured for i2p.

apps:
  i2pbrowser:
    command: usr/bin/I2PBrowser.sh
    desktop: usr/share/applications/i2pbrowser-firefox.desktop
  i2pbrowser-private:
    command: usr/bin/I2PBrowser-Private.sh
    desktop: usr/share/applications/i2pbrowser-firefox-private.desktop

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  i2pbrowser:
    source: https://github.com/eyedeekay/firefox.profile.i2p.git
    source-subdir: "."
    plugin: make
    stage:
      - usr/lib/firefox.profile.i2p/firefox.profile.i2p
      - usr/lib/firefox.profile.i2p/install.sh
      - usr/bin/I2PBrowser.sh
      - usr/bin/I2PBrowser-Private.sh
      - usr/share/applications/i2pbrowser-firefox.desktop
      - usr/share/applications/i2pbrowser-firefox-private.desktop
    prime:
      - usr/lib/firefox.profile.i2p/firefox.profile.i2p
      - usr/lib/firefox.profile.i2p/install.sh
      - usr/bin/I2PBrowser.sh
      - usr/bin/I2PBrowser-Private.sh
      - usr/share/applications/i2pbrowser-firefox.desktop
      - usr/share/applications//i2pbrowser-firefox-private.desktop
    stage-packages: [ firefox ]



