name: i2pbrowser
version: '0.05b'
summary: I2P Browser Launcher
base: core18
description: |
  This snap contains a script which automatically configures and launches a
  Firefox browser configured for i2p.

apps:
  i2pbrowser:
    command: desktop-launch $SNAP/usr/bin/I2PBrowser.sh
    desktop: usr/share/applications/i2pbrowser-firefox.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
    #environment:
      #DISPLAY: 0
  private:
    command: desktop-launch $SNAP/usr/bin/I2PBrowser-Private.sh
    desktop: usr/share/applications/i2pbrowser-firefox-private.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
    #environment:
      #DISPLAY: 0
  debug:
    command: desktop-launch $SNAP/usr/bin/I2PBrowser-Debug.sh
    desktop: usr/share/applications/i2pbrowser-firefox-debug.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
    #environment:
      #DISPLAY: 0

grade: stable
confinement: strict

parts:
  desktop-gtk:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - libgtk-3-bin
      - unity-gtk2-module
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk
      - ibus-gtk3
      - libibus-1.0-5
    after: [desktop-patch]
    override-pull: |
      snapcraftctl pull
      patch -Np1 < $SNAPCRAFT_STAGE/desktop-launch.patch
    organize:
        usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0: usr/lib/gtk-2.0
        usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0: usr/lib/gtk-3.0

  desktop-patch:
    source: patches
    plugin: dump
    prime: [-*]

  i2pbrowser:
    after: [desktop-gtk3]
    source: https://github.com/eyedeekay/firefox.profile.i2p.git
    source-subdir: "."
    plugin: make
    make-parameters:
        - DESTDIR=$SNAPCRAFT_PART_INSTALL
        - SNAP_USER_COMMON=$SNAP_USER_COMMON
        - SNAP_USER_DATA=$SNAP_USER_DATA
        - install-extensions-syswide
        - install-snap-commondir
        - install
    stage:
      - .
    prime:
      - .
    stage-packages:
      - firefox
      - libgtkextra-dev
      - libpng-dev
      - libgtk-3-dev
      - libgdk-pixbuf2.0-dev


